<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="x-apple-disable-message-reformatting">
        <title></title>
    </head>
    <body>
        <h1>Welcome</h1>
        <p>Dear ${username},</p>
        <p>Finish creating your account.</p>
        <p>We're excited to have you get started on WebJournal. First, you need to confirm your account. Just press the link below.</p>
        <a href="${verificationURL}">Verify email</a>
    </body>
</html>